export const canonicalPublicRoutes = [
  "/",
  "/buyers",
  "/sellers",
  "/investors",
  "/renters",
  "/markets",
  "/guides",
  "/articles",
  "/videos",
  "/ai",
  "/about",
  "/intake",
  "/resources",
  "/tools",
  "/privacypolicy",
  "/terms",
  "/accessibility",
] as const;

export const noIndexRoutePrefixes = [
  "/landing",
  "/squeeze",
  "/docs",
  "/brands",
  "/network",
  "/kpi",
  "/case-studies",
  "/login",
  "/account",
  "/auth",
  "/thank-you",
  "/lead-magnets",
  "/monkeymaghees",
] as const;
