create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  role text not null check (role in ('admin', 'author', 'member')),
  created_at timestamptz not null default now(),
  unique (user_id, role)
);

create table if not exists public.entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  tier text not null default 'free' check (tier in ('free', 'pro')),
  status text not null default 'active' check (status in ('active', 'inactive')),
  source text not null default 'default',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stripe_customers (
  id bigint generated by default as identity primary key,
  user_id uuid unique,
  stripe_customer_id text not null unique,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid,
  stripe_customer_id text references public.stripe_customers(stripe_customer_id) on delete set null,
  stripe_subscription_id text not null unique,
  price_id text,
  status text not null,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.asset_jobs (
  id bigint generated by default as identity primary key,
  asset_id bigint not null references public.assets(id) on delete cascade,
  queue_job_id text unique,
  status text not null check (status in ('queued', 'processing', 'completed', 'failed', 'skipped', 'queue_failed')),
  attempts integer not null default 0,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.asset_text_chunks (
  id bigint generated by default as identity primary key,
  asset_id bigint not null references public.assets(id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  created_at timestamptz not null default now(),
  unique (asset_id, chunk_index)
);

create index if not exists idx_assets_status on public.assets(status);
create index if not exists idx_assets_kind_status on public.assets(kind, status);
create index if not exists idx_asset_jobs_asset_id on public.asset_jobs(asset_id);
create index if not exists idx_asset_jobs_status on public.asset_jobs(status);
create index if not exists idx_entitlements_tier on public.entitlements(tier);
