create table if not exists public.pro_waitlist (
  id bigint generated by default as identity primary key,
  email text not null,
  slug text not null,
  source text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (email, slug)
);

create table if not exists public.stripe_events (
  id bigint generated by default as identity primary key,
  stripe_event_id text not null unique,
  event_type text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  public_id text unique,
  secure_url text,
  preview_url text,
  access text not null default 'public',
  kind text not null default 'raw',
  status text not null default 'processing',
  storage_provider text not null default 'cloudinary',
  downloadable boolean not null default true,
  bytes bigint,
  format text,
  width integer,
  height integer,
  duration numeric,
  pages integer,
  original_filename text,
  context jsonb,
  tags jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
